### ISSUE TITLE
Google Drive is unusable

### ISSUE THREAD

**Issue by chrsmlls333** [SirFlip/docker-FreeFileSync#1]
Great work on this docker! I have found a lot of use from it. But. The cloud functions are unfortunately unusable. 

When I try to register my drive user, I think it is trying to open a browser to do the handshake/OAuth/token-giving, but I'm not sure if that's possible. It just does nothing. 

Please let me know if there is a way to sideload the token in the config folders etc. Thanks!

**Comment by chrsmlls333** [comment]
Actually I may have just fixed this by consoling in and installing first xdg-tools (may be unnecessary) then midori (to be replaced with the lightest browser you can find) with apt. 

After this, the Add Connection button opened its login page properly.

Sidenote, the login info/token is not persistent between runs of the docker.

**Comment by SirFlip** [comment]
Thanks, I have a look at it.  I never used the Google drive feature so no testing ;).  But your fix is working.  It seams like xdo-tools are necessary to open the browser from FileSync.
I think that it does not save the token is the same problem, that it does not save the open jobs either between sessions.  Looks like FileSync does not handle the SIGTREM properly and just exits without saving the global config.
Workaround is to close it from in the Program via "File -> Exit" then everything gets saved.

**Comment by SirFlip** [comment]
I put the token problem in its own issue #2

**Comment by chrsmlls333** [comment]
Thanks for the quick turnaround on this!
